## This is the configuration file for Headroom.
## See https://github.com/vaclavsvejcar/headroom for more details.

run-mode: replace

source-paths:
    - src
    - example/src

excluded-paths: []

template-paths:
    - .headroom-templates

variables:
    project: Monarch
    year: '2020'
    maintainer_name: Mohammad Hasani
    maintainer_email: the-dr-lazy@pm.me
    maintainer_comment: the-dr-lazy.github.io

license-headers:
    purescript:
        margin-after: 1
        block-comment:
            starts-with: '{-|'
            ends-with: '-}'
    js:
        file-extensions:
            - js
            - ts
        margin-after: 1

post-process:
    update-copyright:
        enabled: true
